### ISSUE TITLE
Can't run server

### ISSUE THREAD

**Issue by cjohnson1341** [vechema/dnd-web#3]
I've installed both Java and Maven and when I go to run `mvn spring-boot:run`, it seems to build, but when I go to server link you posted the link doesn't work. I noticed in your pom.xml file that you are using something called 'h2database'. Do I need to install that or somehow use that to see the backend?

**Comment by vechema** [comment]
Maven should install all dependencies you need. I've been playing with the server a lot lately and I try to commit it in a working state but it doesn't always happen. Can you share some of the console output from running `mvn spring-boot:run` and what you see when you go to http://localhost:8080/

**Comment by cjohnson1341** [comment]
Here is an error that I found about 3/4 of the way through the build:
<img width="1284" alt="screen shot 2019-02-27 at 5 39 47 pm" src="https://user-images.githubusercontent.com/33328629/53533121-d431c080-3ab6-11e9-8acd-f02b70d8877e.png">
And then here is the end where it says it built successfully:
<img width="1286" alt="screen shot 2019-02-27 at 5 40 00 pm" src="https://user-images.githubusercontent.com/33328629/53533135-e01d8280-3ab6-11e9-8601-ee3acc436d6c.png">
I got the general "site can't be reached" error
<img width="1082" alt="screen shot 2019-02-27 at 5 41 28 pm" src="https://user-images.githubusercontent.com/33328629/53533165-f88d9d00-3ab6-11e9-9d80-1c643aa98895.png">

**Comment by vechema** [comment]
It's saying it's missing the AbilityScore.json file which should be in server/src/main/resources/database/. This file: https://github.com/vechema/dnd-web/blob/master/server/src/main/resources/database/AbilityScore.json Do you have that file locally?

**Comment by cjohnson1341** [comment]
Huh interesting. Yea I have the file locally and it opens in VS code with everything in it.

**Comment by vechema** [comment]
I don't know what else to do remotely. I can definitely help when we get together

**Comment by vechema** [comment]
Turns out the issue was self induced. I was hard coding Windows file separator characters instead of getting Java to do OS indepenent ones. Fixed
